export default {
  steemit: 'Steemit',
  cocozl: 'cocozl',
  esteem: 'eSteem',
  chainbb: 'chainBB',
  utopian: 'Utopian',
  dtube: 'DTube',
  dlive: 'DLive',
  dmania: 'dMania',
  dsound: 'DSound',
  steepshot: 'Steepshot',
  zappl: 'Zappl',
  steemkr: 'Steemkr',
  timer: 'Timer',
  steemjs: 'Steem.js',
  strimi: 'Strimi',
};
